//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecci.inv.system.ProductRawService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductRawService.ProdRawSoap")]
    public interface ProdRawSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductRaw", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetProductRaw();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductRaw", ReplyAction="*")]
        System.Threading.Tasks.Task GetProductRawAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowDeliveredById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ShowDeliveredById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowDeliveredById", ReplyAction="*")]
        System.Threading.Tasks.Task ShowDeliveredByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDispatch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int UpdateDispatch(int upid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDispatch", ReplyAction="*")]
        System.Threading.Tasks.Task<int> UpdateDispatchAsync(int upid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProdRawSoapChannel : ecci.inv.system.ProductRawService.ProdRawSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProdRawSoapClient : System.ServiceModel.ClientBase<ecci.inv.system.ProductRawService.ProdRawSoap>, ecci.inv.system.ProductRawService.ProdRawSoap {
        
        public ProdRawSoapClient() {
        }
        
        public ProdRawSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProdRawSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdRawSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdRawSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GetProductRaw() {
            base.Channel.GetProductRaw();
        }
        
        public System.Threading.Tasks.Task GetProductRawAsync() {
            return base.Channel.GetProductRawAsync();
        }
        
        public void ShowDeliveredById(int id) {
            base.Channel.ShowDeliveredById(id);
        }
        
        public System.Threading.Tasks.Task ShowDeliveredByIdAsync(int id) {
            return base.Channel.ShowDeliveredByIdAsync(id);
        }
        
        public int UpdateDispatch(int upid) {
            return base.Channel.UpdateDispatch(upid);
        }
        
        public System.Threading.Tasks.Task<int> UpdateDispatchAsync(int upid) {
            return base.Channel.UpdateDispatchAsync(upid);
        }
    }
}
