//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecci.inv.system.OnholdService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OnholdService.OnHoldServiceSoap")]
    public interface OnHoldServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOnHoldItems", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetOnHoldItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOnHoldItems", ReplyAction="*")]
        System.Threading.Tasks.Task GetOnHoldItemsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowDeliveredById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ShowDeliveredById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowDeliveredById", ReplyAction="*")]
        System.Threading.Tasks.Task ShowDeliveredByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDispatch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int UpdateDispatch(int upid, int rework, int returns, int scrap);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDispatch", ReplyAction="*")]
        System.Threading.Tasks.Task<int> UpdateDispatchAsync(int upid, int rework, int returns, int scrap);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OnHoldServiceSoapChannel : ecci.inv.system.OnholdService.OnHoldServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OnHoldServiceSoapClient : System.ServiceModel.ClientBase<ecci.inv.system.OnholdService.OnHoldServiceSoap>, ecci.inv.system.OnholdService.OnHoldServiceSoap {
        
        public OnHoldServiceSoapClient() {
        }
        
        public OnHoldServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OnHoldServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OnHoldServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OnHoldServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GetOnHoldItems() {
            base.Channel.GetOnHoldItems();
        }
        
        public System.Threading.Tasks.Task GetOnHoldItemsAsync() {
            return base.Channel.GetOnHoldItemsAsync();
        }
        
        public void ShowDeliveredById(int id) {
            base.Channel.ShowDeliveredById(id);
        }
        
        public System.Threading.Tasks.Task ShowDeliveredByIdAsync(int id) {
            return base.Channel.ShowDeliveredByIdAsync(id);
        }
        
        public int UpdateDispatch(int upid, int rework, int returns, int scrap) {
            return base.Channel.UpdateDispatch(upid, rework, returns, scrap);
        }
        
        public System.Threading.Tasks.Task<int> UpdateDispatchAsync(int upid, int rework, int returns, int scrap) {
            return base.Channel.UpdateDispatchAsync(upid, rework, returns, scrap);
        }
    }
}
