//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecci.inv.system.ManageClientService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ManageClientService.ManageClientServiceSoap")]
    public interface ManageClientServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetClient", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetClient();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetClient", ReplyAction="*")]
        System.Threading.Tasks.Task GetClientAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetClientById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetClientById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetClientById", ReplyAction="*")]
        System.Threading.Tasks.Task GetClientByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateClientById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int updateClientById(int clid, string address, string contact, string contact2, int stat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateClientById", ReplyAction="*")]
        System.Threading.Tasks.Task<int> updateClientByIdAsync(int clid, string address, string contact, string contact2, int stat);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ManageClientServiceSoapChannel : ecci.inv.system.ManageClientService.ManageClientServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ManageClientServiceSoapClient : System.ServiceModel.ClientBase<ecci.inv.system.ManageClientService.ManageClientServiceSoap>, ecci.inv.system.ManageClientService.ManageClientServiceSoap {
        
        public ManageClientServiceSoapClient() {
        }
        
        public ManageClientServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ManageClientServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManageClientServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManageClientServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GetClient() {
            base.Channel.GetClient();
        }
        
        public System.Threading.Tasks.Task GetClientAsync() {
            return base.Channel.GetClientAsync();
        }
        
        public void GetClientById(int id) {
            base.Channel.GetClientById(id);
        }
        
        public System.Threading.Tasks.Task GetClientByIdAsync(int id) {
            return base.Channel.GetClientByIdAsync(id);
        }
        
        public int updateClientById(int clid, string address, string contact, string contact2, int stat) {
            return base.Channel.updateClientById(clid, address, contact, contact2, stat);
        }
        
        public System.Threading.Tasks.Task<int> updateClientByIdAsync(int clid, string address, string contact, string contact2, int stat) {
            return base.Channel.updateClientByIdAsync(clid, address, contact, contact2, stat);
        }
    }
}
