//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecci.inv.system.ProductOrderService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductOrderService.ProductOrderServiceSoap")]
    public interface ProductOrderServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPurchaseOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetPurchaseOrder();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPurchaseOrder", ReplyAction="*")]
        System.Threading.Tasks.Task GetPurchaseOrderAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductOrderServiceSoapChannel : ecci.inv.system.ProductOrderService.ProductOrderServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductOrderServiceSoapClient : System.ServiceModel.ClientBase<ecci.inv.system.ProductOrderService.ProductOrderServiceSoap>, ecci.inv.system.ProductOrderService.ProductOrderServiceSoap {
        
        public ProductOrderServiceSoapClient() {
        }
        
        public ProductOrderServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductOrderServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductOrderServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductOrderServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GetPurchaseOrder() {
            base.Channel.GetPurchaseOrder();
        }
        
        public System.Threading.Tasks.Task GetPurchaseOrderAsync() {
            return base.Channel.GetPurchaseOrderAsync();
        }
    }
}
