//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecci.inv.system.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ManageItemServiceSoap")]
    public interface ManageItemServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItem", ReplyAction="*")]
        void GetItem();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItem", ReplyAction="*")]
        System.Threading.Tasks.Task GetItemAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ManageItemServiceSoapChannel : ecci.inv.system.ServiceReference1.ManageItemServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ManageItemServiceSoapClient : System.ServiceModel.ClientBase<ecci.inv.system.ServiceReference1.ManageItemServiceSoap>, ecci.inv.system.ServiceReference1.ManageItemServiceSoap {
        
        public ManageItemServiceSoapClient() {
        }
        
        public ManageItemServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ManageItemServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManageItemServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManageItemServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GetItem() {
            base.Channel.GetItem();
        }
        
        public System.Threading.Tasks.Task GetItemAsync() {
            return base.Channel.GetItemAsync();
        }
    }
}
