//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecci.inv.system.ManageItemService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ManageItemService.ManageItemServiceSoap")]
    public interface ManageItemServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetItem();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItem", ReplyAction="*")]
        System.Threading.Tasks.Task GetItemAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItemById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetItemById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItemById", ReplyAction="*")]
        System.Threading.Tasks.Task GetItemByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateItemById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int updateItemById(int iid, decimal iprice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateItemById", ReplyAction="*")]
        System.Threading.Tasks.Task<int> updateItemByIdAsync(int iid, decimal iprice);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ManageItemServiceSoapChannel : ecci.inv.system.ManageItemService.ManageItemServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ManageItemServiceSoapClient : System.ServiceModel.ClientBase<ecci.inv.system.ManageItemService.ManageItemServiceSoap>, ecci.inv.system.ManageItemService.ManageItemServiceSoap {
        
        public ManageItemServiceSoapClient() {
        }
        
        public ManageItemServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ManageItemServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManageItemServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManageItemServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GetItem() {
            base.Channel.GetItem();
        }
        
        public System.Threading.Tasks.Task GetItemAsync() {
            return base.Channel.GetItemAsync();
        }
        
        public void GetItemById(int id) {
            base.Channel.GetItemById(id);
        }
        
        public System.Threading.Tasks.Task GetItemByIdAsync(int id) {
            return base.Channel.GetItemByIdAsync(id);
        }
        
        public int updateItemById(int iid, decimal iprice) {
            return base.Channel.updateItemById(iid, iprice);
        }
        
        public System.Threading.Tasks.Task<int> updateItemByIdAsync(int iid, decimal iprice) {
            return base.Channel.updateItemByIdAsync(iid, iprice);
        }
    }
}
