//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecci.inv.system.ServiceReference3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.PurchaseOrderServiceSoap")]
    public interface PurchaseOrderServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPurchaseOrder", ReplyAction="*")]
        void GetPurchaseOrder();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPurchaseOrder", ReplyAction="*")]
        System.Threading.Tasks.Task GetPurchaseOrderAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PurchaseOrderServiceSoapChannel : ecci.inv.system.ServiceReference3.PurchaseOrderServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PurchaseOrderServiceSoapClient : System.ServiceModel.ClientBase<ecci.inv.system.ServiceReference3.PurchaseOrderServiceSoap>, ecci.inv.system.ServiceReference3.PurchaseOrderServiceSoap {
        
        public PurchaseOrderServiceSoapClient() {
        }
        
        public PurchaseOrderServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PurchaseOrderServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurchaseOrderServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurchaseOrderServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GetPurchaseOrder() {
            base.Channel.GetPurchaseOrder();
        }
        
        public System.Threading.Tasks.Task GetPurchaseOrderAsync() {
            return base.Channel.GetPurchaseOrderAsync();
        }
    }
}
