//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecci.inv.system.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.ManageSupplierServiceSoap")]
    public interface ManageSupplierServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSupplier", ReplyAction="*")]
        void GetSupplier();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSupplier", ReplyAction="*")]
        System.Threading.Tasks.Task GetSupplierAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ManageSupplierServiceSoapChannel : ecci.inv.system.ServiceReference2.ManageSupplierServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ManageSupplierServiceSoapClient : System.ServiceModel.ClientBase<ecci.inv.system.ServiceReference2.ManageSupplierServiceSoap>, ecci.inv.system.ServiceReference2.ManageSupplierServiceSoap {
        
        public ManageSupplierServiceSoapClient() {
        }
        
        public ManageSupplierServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ManageSupplierServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManageSupplierServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManageSupplierServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GetSupplier() {
            base.Channel.GetSupplier();
        }
        
        public System.Threading.Tasks.Task GetSupplierAsync() {
            return base.Channel.GetSupplierAsync();
        }
    }
}
