//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecci.inv.system.DeliveryService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DeliveryService.OrderDeliveryServiceSoap")]
    public interface OrderDeliveryServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeliveredOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetDeliveredOrder();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeliveredOrder", ReplyAction="*")]
        System.Threading.Tasks.Task GetDeliveredOrderAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowDeliveredById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ShowDeliveredById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowDeliveredById", ReplyAction="*")]
        System.Threading.Tasks.Task ShowDeliveredByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int UpdateById(int upid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateById", ReplyAction="*")]
        System.Threading.Tasks.Task<int> UpdateByIdAsync(int upid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OrderDeliveryServiceSoapChannel : ecci.inv.system.DeliveryService.OrderDeliveryServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderDeliveryServiceSoapClient : System.ServiceModel.ClientBase<ecci.inv.system.DeliveryService.OrderDeliveryServiceSoap>, ecci.inv.system.DeliveryService.OrderDeliveryServiceSoap {
        
        public OrderDeliveryServiceSoapClient() {
        }
        
        public OrderDeliveryServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderDeliveryServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderDeliveryServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderDeliveryServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GetDeliveredOrder() {
            base.Channel.GetDeliveredOrder();
        }
        
        public System.Threading.Tasks.Task GetDeliveredOrderAsync() {
            return base.Channel.GetDeliveredOrderAsync();
        }
        
        public void ShowDeliveredById(int id) {
            base.Channel.ShowDeliveredById(id);
        }
        
        public System.Threading.Tasks.Task ShowDeliveredByIdAsync(int id) {
            return base.Channel.ShowDeliveredByIdAsync(id);
        }
        
        public int UpdateById(int upid) {
            return base.Channel.UpdateById(upid);
        }
        
        public System.Threading.Tasks.Task<int> UpdateByIdAsync(int upid) {
            return base.Channel.UpdateByIdAsync(upid);
        }
    }
}
