//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecci.inv.system.DispatchService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DispatchService.DispatchingDeliveryServiceSoap")]
    public interface DispatchingDeliveryServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DispatchDelivery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DispatchDelivery();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DispatchDelivery", ReplyAction="*")]
        System.Threading.Tasks.Task DispatchDeliveryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowDeliveredById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ShowDeliveredById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowDeliveredById", ReplyAction="*")]
        System.Threading.Tasks.Task ShowDeliveredByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDispatch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int UpdateDispatch(int upid, int dq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDispatch", ReplyAction="*")]
        System.Threading.Tasks.Task<int> UpdateDispatchAsync(int upid, int dq);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DispatchingDeliveryServiceSoapChannel : ecci.inv.system.DispatchService.DispatchingDeliveryServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DispatchingDeliveryServiceSoapClient : System.ServiceModel.ClientBase<ecci.inv.system.DispatchService.DispatchingDeliveryServiceSoap>, ecci.inv.system.DispatchService.DispatchingDeliveryServiceSoap {
        
        public DispatchingDeliveryServiceSoapClient() {
        }
        
        public DispatchingDeliveryServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DispatchingDeliveryServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DispatchingDeliveryServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DispatchingDeliveryServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DispatchDelivery() {
            base.Channel.DispatchDelivery();
        }
        
        public System.Threading.Tasks.Task DispatchDeliveryAsync() {
            return base.Channel.DispatchDeliveryAsync();
        }
        
        public void ShowDeliveredById(int id) {
            base.Channel.ShowDeliveredById(id);
        }
        
        public System.Threading.Tasks.Task ShowDeliveredByIdAsync(int id) {
            return base.Channel.ShowDeliveredByIdAsync(id);
        }
        
        public int UpdateDispatch(int upid, int dq) {
            return base.Channel.UpdateDispatch(upid, dq);
        }
        
        public System.Threading.Tasks.Task<int> UpdateDispatchAsync(int upid, int dq) {
            return base.Channel.UpdateDispatchAsync(upid, dq);
        }
    }
}
