//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecci.inv.system.ManageSupplierService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ManageSupplierService.ManageSupplierServiceSoap")]
    public interface ManageSupplierServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSupplier", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetSupplier();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSupplier", ReplyAction="*")]
        System.Threading.Tasks.Task GetSupplierAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSupplierById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetSupplierById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSupplierById", ReplyAction="*")]
        System.Threading.Tasks.Task GetSupplierByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateSupplierById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int updateSupplierById(int spid, string address, string contact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateSupplierById", ReplyAction="*")]
        System.Threading.Tasks.Task<int> updateSupplierByIdAsync(int spid, string address, string contact);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ManageSupplierServiceSoapChannel : ecci.inv.system.ManageSupplierService.ManageSupplierServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ManageSupplierServiceSoapClient : System.ServiceModel.ClientBase<ecci.inv.system.ManageSupplierService.ManageSupplierServiceSoap>, ecci.inv.system.ManageSupplierService.ManageSupplierServiceSoap {
        
        public ManageSupplierServiceSoapClient() {
        }
        
        public ManageSupplierServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ManageSupplierServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManageSupplierServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManageSupplierServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GetSupplier() {
            base.Channel.GetSupplier();
        }
        
        public System.Threading.Tasks.Task GetSupplierAsync() {
            return base.Channel.GetSupplierAsync();
        }
        
        public void GetSupplierById(int id) {
            base.Channel.GetSupplierById(id);
        }
        
        public System.Threading.Tasks.Task GetSupplierByIdAsync(int id) {
            return base.Channel.GetSupplierByIdAsync(id);
        }
        
        public int updateSupplierById(int spid, string address, string contact) {
            return base.Channel.updateSupplierById(spid, address, contact);
        }
        
        public System.Threading.Tasks.Task<int> updateSupplierByIdAsync(int spid, string address, string contact) {
            return base.Channel.updateSupplierByIdAsync(spid, address, contact);
        }
    }
}
